"""auto update

Revision ID: 72519a76aa7e
Revises: c2f309a21bc0
Create Date: 2026-10-08 05:15:41.207531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72519a76aa7e'
down_revision: Union[str, Sequence[str], None] = 'c2f309a21bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('migration_tasks', sa.Column('sync_mode', sa.String(), nullable=True))
    op.add_column('migration_tasks', sa.Column('verify', sa.Boolean(), nullable=True))
    op.add_column('migration_tasks', sa.Column('concurrency', sa.Integer(), nullable=True))
    op.add_column('migration_tasks', sa.Column('bandwidth_mbps', sa.Float(), nullable=True))
    op.add_column('migration_tasks', sa.Column('include_suffixes', sa.String(), nullable=True))
    op.add_column('migration_tasks', sa.Column('exclude_suffixes', sa.String(), nullable=True))
    op.add_column('migration_tasks', sa.Column('min_size', sa.Float(), nullable=True))
    op.add_column('migration_tasks', sa.Column('max_size', sa.Float(), nullable=True))
    op.add_column('migration_tasks', sa.Column('modified_after', sa.String(), nullable=True))
    op.add_column('migration_tasks', sa.Column('modified_before', sa.String(), nullable=True))
    op.add_column('migration_tasks', sa.Column('prefix_queue', sa.String(), nullable=True))
    op.add_column('migration_tasks', sa.Column('total_bytes', sa.Float(), nullable=True))
    op.add_column('migration_tasks', sa.Column('verified_count', sa.Integer(), nullable=True))
    op.add_column('migration_tasks', sa.Column('bytes_copied', sa.Float(), nullable=True))
    op.add_column('migration_tasks', sa.Column('processed_bytes', sa.Float(), nullable=True))
    op.add_column('migration_tasks', sa.Column('logs', sa.String(), nullable=True))
    op.add_column('migration_tasks', sa.Column('locked_until', sa.Float(), nullable=True))
    op.add_column('migration_tasks', sa.Column('last_run_at', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('migration_tasks', 'last_run_at')
    op.drop_column('migration_tasks', 'locked_until')
    op.drop_column('migration_tasks', 'logs')
    op.drop_column('migration_tasks', 'processed_bytes')
    op.drop_column('migration_tasks', 'bytes_copied')
    op.drop_column('migration_tasks', 'verified_count')
    op.drop_column('migration_tasks', 'total_bytes')
    op.drop_column('migration_tasks', 'prefix_queue')
    op.drop_column('migration_tasks', 'modified_before')
    op.drop_column('migration_tasks', 'modified_after')
    op.drop_column('migration_tasks', 'max_size')
    op.drop_column('migration_tasks', 'min_size')
    op.drop_column('migration_tasks', 'exclude_suffixes')
    op.drop_column('migration_tasks', 'include_suffixes')
    op.drop_column('migration_tasks', 'bandwidth_mbps')
    op.drop_column('migration_tasks', 'concurrency')
    op.drop_column('migration_tasks', 'verify')
    op.drop_column('migration_tasks', 'sync_mode')
    # ### end Alembic commands ###