"""auto update

Revision ID: c2f309a21bc0
Revises: f5ba2b31ad06
Create Date: 2026-10-08 02:53:33.955999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2f309a21bc0'
down_revision: Union[str, Sequence[str], None] = 'f5ba2b31ad06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migration_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('source_prefix', sa.String(), nullable=True),
    sa.Column('target_prefix', sa.String(), nullable=True),
    sa.Column('skip_existing', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('continuation_token', sa.String(), nullable=True),
    sa.Column('listing_done', sa.Boolean(), nullable=True),
    sa.Column('pending_keys', sa.String(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('done_count', sa.Integer(), nullable=True),
    sa.Column('skipped_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('bytes_transferred', sa.Integer(), nullable=True),
    sa.Column('failed_items', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_migration_tasks_source_id'), 'migration_tasks', ['source_id'], unique=False)
    op.create_index(op.f('ix_migration_tasks_target_id'), 'migration_tasks', ['target_id'], unique=False)
    op.create_index(op.f('ix_migration_tasks_user_id'), 'migration_tasks', ['user_id'], unique=False)
    op.create_table('storage_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('access_key', sa.String(), nullable=False),
    sa.Column('secret_key', sa.String(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('path_style', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_connections_user_id'), 'storage_connections', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storage_connections_user_id'), table_name='storage_connections')
    op.drop_table('storage_connections')
    op.drop_index(op.f('ix_migration_tasks_user_id'), table_name='migration_tasks')
    op.drop_index(op.f('ix_migration_tasks_target_id'), table_name='migration_tasks')
    op.drop_index(op.f('ix_migration_tasks_source_id'), table_name='migration_tasks')
    op.drop_table('migration_tasks')
    # ### end Alembic commands ###